[package]
name = "discord_ping_spam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
serde = "1.0.160"
serde_json = "1"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
